#!/usr/bin/env node

/**
 * Flowise Setup Helper Script
 * 
 * This script helps you set up your .env.local file with Flowise configuration.
 * 
 * Usage:
 *   node setup-flowise.js
 * 
 * Or make it executable and run:
 *   chmod +x setup-flowise.js
 *   ./setup-flowise.js
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(query) {
  return new Promise(resolve => rl.question(query, resolve));
}

async function setup() {
  console.log('\n🚀 Flowise Integration Setup\n');
  console.log('This script will help you create your .env.local file.\n');

  // Check if .env.local already exists
  const envPath = path.join(process.cwd(), '.env.local');
  if (fs.existsSync(envPath)) {
    const overwrite = await question('⚠️  .env.local already exists. Overwrite? (y/n): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('\n❌ Setup cancelled.');
      rl.close();
      return;
    }
  }

  // Get Flowise API URL
  console.log('\n📡 Flowise API Configuration');
  console.log('Where is your Flowise instance running?');
  console.log('  - Local: http://localhost:3000');
  console.log('  - Render: https://your-service.onrender.com');
  console.log('  - Railway: https://your-service.railway.app');
  const apiUrl = await question('Flowise API URL [http://localhost:3000]: ') || 'http://localhost:3000';
  
  // Get API Key (optional)
  console.log('\n🔑 Flowise API Key (Optional)');
  console.log('If your Flowise instance requires API key authentication, enter it here.');
  console.log('Leave blank if no API key is required.\n');
  const apiKey = await question('Flowise API Key (optional): ');

  // Get Chatflow ID
  console.log('\n🆔 Chatflow ID');
  console.log('You can find your Chatflow ID by:');
  console.log('  1. Opening Flowise dashboard');
  console.log('  2. Clicking on your chatflow');
  console.log('  3. Looking at the URL: http://localhost:3000/chatflow/YOUR_ID_HERE');
  console.log('  4. Or run: curl http://localhost:3000/api/v1/chatflows\n');
  const chatflowId = await question('Enter your Chatflow ID: ');

  if (!chatflowId.trim()) {
    console.log('\n❌ Chatflow ID is required. Setup cancelled.');
    rl.close();
    return;
  }

  // Create .env.local content
  let envContent = `# Flowise Configuration
# Generated by setup-flowise.js

# Flowise API URL
NEXT_PUBLIC_FLOWISE_API_URL=${apiUrl.trim()}

# Flowise Chatflow ID
NEXT_PUBLIC_FLOWISE_CHATFLOW_ID=${chatflowId.trim()}
`;

  // Add API key if provided
  if (apiKey && apiKey.trim()) {
    envContent += `
# Flowise API Key (for authentication)
NEXT_PUBLIC_FLOWISE_API_KEY=${apiKey.trim()}
`;
  }

  // Write .env.local
  try {
    fs.writeFileSync(envPath, envContent);
    console.log('\n✅ Success! .env.local file created.\n');
    console.log('📝 Configuration:');
    console.log(`   API URL: ${apiUrl}`);
    console.log(`   Chatflow ID: ${chatflowId}`);
    if (apiKey && apiKey.trim()) {
      console.log(`   API Key: ${'*'.repeat(Math.min(apiKey.length, 20))} (hidden)`);
    }
    console.log();
    console.log('📋 Next steps:');
    if (apiUrl.includes('localhost') || apiUrl.includes('127.0.0.1')) {
      console.log('   1. Make sure Flowise is running: flowise start');
      console.log('   2. Start your Next.js app: npm run dev');
      console.log('   3. Test the integration in your browser\n');
    } else {
      console.log('   1. Verify Flowise is accessible at:', apiUrl);
      console.log('   2. Start your Next.js app: npm run dev');
      console.log('   3. Test the integration in your browser\n');
    }
  } catch (error) {
    console.error('\n❌ Error creating .env.local:', error.message);
  }

  rl.close();
}

// Run setup
setup().catch(error => {
  console.error('\n❌ Setup failed:', error);
  rl.close();
  process.exit(1);
});

